version: "3.8"
services:
  backend:
    container_name: backend
    expose:
      - "80"
    build:
      context: ./backend
    command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "80", "--proxy-headers", "--reload"]
  frontend:
    container_name: frontend
    ports:
      - "3000:3000"
    build:
      context: ./frontend
    depends_on:
      - backend
